name: template-R-SC-2026

channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  # Jupyter dependencies
  - jupyterlab>=4.6
  - jupyter-rsession-proxy  
  
  # Python environment
  - python>=3.13
  - pip
  - pip:
    - watermark

  # R environment
  - rstudio-desktop
  - r-irkernel
  - r-base
  - r-essentials
  
  # For the M2 RNAseq course:
  - fastqc
  - fastp
  - fastq-screen
  - samtools
  - multiqc
  - qualimap
  - bedtools
  - htseq
  - star
  - subread
  - salmon
