#!/bin/bash
set -e

PATH='/srv/conda/envs/notebook/bin:$PATH'
R_HOME='/srv/conda/envs/notebook/lib/R'

# S'assurer que rserver est dans le PATH (souvent déjà /usr/lib/rstudio-server/bin/rserver)
# Vérification (optionnelle, pour debug)
if ! command -v rserver &> /dev/null; then
    # chemin typique avec rstudio-server .deb
    export PATH="/usr/lib/rstudio-server/bin:$PATH"
fi

# Optionnel : vérifier que rserver est bien trouvable
command -v rserver || { echo "rserver introuvable, problème d'installation RStudio"; exit 1; }

# Juste s'assurer que le kernel R est bien enregistré
R --quiet -e "IRkernel::installspec(prefix='/srv/conda/envs/notebook')" || true


# Install Bash kernel
# python -m bash_kernel.install --sys-prefix

# Install R package
# if not available as conda package
# R -e "install.packages('diagram', repos='http://cran.rstudio.com/')"

# Install R/Bioconductor package
# if not available as conda package

# First install Bioconductor package manager
# https://bioconductor.org/install/
# R -e "install.packages('BiocManager', repos='http://cran.rstudio.com/')"
# R -e "BiocManager::install()"

# Then install required packages
# Biostrings: Efficient manipulation of biological strings
# https://bioconductor.org/packages/release/bioc/html/Biostrings.html
# R -e "BiocManager::install('Biostrings')"
